### ISSUE TITLE
Cannot run the application; resource error

### ISSUE THREAD

**Issue by virtualbiz** [MykolaKovalchuk/SAE5#1]
![image](https://user-images.githubusercontent.com/50282257/59609138-6da9de80-9149-11e9-9e39-165748947263.png)

**Comment by MykolaKovalchuk** [comment]
What file is that?
The error is about assigning an icon from resources. Try to comment that line out.
Also what IDE do you use? Should work with Ms Visual Studio.

**Comment by virtualbiz** [comment]
I do use Visual Studio 2019 enterprise edition. After I commented out this line and tried to run it from Ctrl+F5, I hit this error instead:

![image](https://user-images.githubusercontent.com/50282257/59778048-535a3700-92e8-11e9-8718-eab70cfc6a83.png)

It looks like all the resource files can't work somehow.

**Comment by MykolaKovalchuk** [comment]
Looks like resource files are not in sync with other code for some reason.
I will check it later.

**Comment by MykolaKovalchuk** [comment]
This was caused by how resx files were defined in .csproj files, e.g.:
`
    <EmbeddedResource Include="UserControls\HomeUserControl.resx">
      <DependentUpon>HomeUserControl.cs</DependentUpon>
      **<LogicalName>HomeUserControl.resx</LogicalName>**
    </EmbeddedResource>
`
After removing <LogicalName> lines, it works with my VS2019.

Perhaps project file format has changed since this code was written in 2016 with VS2015, or that line was added by some other tool I used.
