### ISSUE TITLE
Как скачать версию?

### ISSUE THREAD

**Issue by emartynov** [MykolaKovalchuk/SAE5#2]
Можно выложить бинарник на гитхабе?

**Comment by MykolaKovalchuk** [comment]
Скомпилированное приложение доступно только коммерчески на сайте [https://mykola.xyz/stitcharteasy/](https://mykola.xyz/stitcharteasy/)
Открытый исходный код доступен без поддержки и может быть скомпилирован самостоятельно.

**Comment by emartynov** [comment]
Спасибо! Щас прикину охота ли мне клонить и прикрутить GitHub actions быстро :)
И хочется поддержать - моя мама просто души не чает в вашей программе.

**Comment by emartynov** [comment]
Добавьте спонсорство может тут?

**Comment by emartynov** [comment]
Купил. Спасибо!
